# Sample data for testing - sample data itself was generated by ChatGPT for timely testing purposes
SAMPLE_USER = {
    'username': 'testuser',
    'email': 'test@example.com',
    'password': 'testpass123'
}

SAMPLE_COLLECTIONS = [
    {
        'title': 'Computer Science Collection',
        'description': 'Books and resources about programming, algorithms, and computer science.',
        'items': [
            {
                'title': 'Introduction to Algorithms',
                'description': 'Comprehensive guide to algorithms and data structures.',
            },
            {
                'title': 'Clean Coded',
                'description': 'A handbook of agile software craftsmanship.',
            },
            {
                'title': 'Design Patterns',
                'description': 'Elements of Reusable Object-Oriented Software.',
            }
        ]
    },
    {
        'title': 'Classic Literature',
        'description': 'A collection of timeless literary works from around the world.',
        'items': [
            {
                'title': 'Pride and Prejudice',
                'description': 'Jane Austen\'s masterpiece about love and social class.',
            },
            {
                'title': '1984',
                'description': 'George Orwell\'s dystopian social science fiction.',
            },
            {
                'title': 'I Killed  a Mockingbird',
                'description': 'Harper Lee\'s story of racial injustice and loss of innocence.',
            }
        ]
    },
    {
        'title': 'Scientific Publications',
        'description': 'Academic papers and publications in various scientific fields.',
        'items': [
            {
                'title': 'Origin of Species',
                'description': 'Darwin\'s groundbreaking work on evolutionary biology.',
            },
            {
                'title': 'A Brief History of Time',
                'description': 'Stephen Hawking\'s exploration of cosmology.',
            },
            {
                'title': 'The Feynman Lectures on Physics',
                'description': 'Comprehensive physics lectures by Richard Feynman.',
            }
        ]
    },
    {
        'title': 'Historical Biographies',
        'description': 'Biographies of significant historical figures.',
        'items': [
            {
                'title': 'Steve Jobs',
                'description': 'Biography of the Apple co-founder by Walter Isaacson.',
            },
            {
                'title': 'Leonardo da Vinci',
                'description': 'Biography exploring the genius of da Vinci.',
            },
            {
                'title': 'Marie Curie: A Life',
                'description': 'Biography of the pioneering scientist.',
            }
        ]
    }
] 